application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/backend', 'RestaurantAdminController');
Route::resource('/', 'FrontendController');

application/app/Models/Restaurant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Restaurant extends Model
{
    //
}

application/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

application/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

application/app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Restaurant;

class FrontendController extends Controller
{
    /**
     * Allow user to search for closest restaurant.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $restaurants = Restaurant::all();
        return view('frontend/index', ["restaurants" => $restaurants]);
    }
}

application/app/Http/Controllers/RestaurantAdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Restaurant;
use App\Http\Requests\SubmitRestaurant;

class RestaurantAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $restaurants = Restaurant::all();
        return view('restaurantadmin/index', ["restaurants" => $restaurants]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('restaurantadmin/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  SubmitRestaurant  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubmitRestaurant $request)
    {
        $restaurant = new Restaurant;
        $restaurant->name = $request->input('name');
        $restaurant->location = $request->input('location');
        $restaurant->save();

        return redirect()->route('backend.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Restaurant  $restaurant
     * @return \Illuminate\Http\Response
     */
    public function show(Restaurant $restaurant)
    {
         return view('restaurantadmin/show', ["restaurant" => $restaurant]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Restaurant  $restaurant
     * @return \Illuminate\Http\Response
     */
    public function edit(Restaurant $restaurant)
    {
        return view('restaurantadmin/edit', ["restaurant" => $restaurant]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  SubmitRestaurant  $request
     * @param  \App\Models\Restaurant    $restaurant
     * @return \Illuminate\Http\Response
     */
    public function update(SubmitRestaurant $request, Restaurant $restaurant)
    {
        $restaurant->name = $request->input('name');
        $restaurant->location = $request->input('location');
        $restaurant->save();

        return redirect()->route('backend.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Restaurant  $restaurant
     * @return \Illuminate\Http\Response
     */
    public function destroy(Restaurant $restaurant)
    {
        $restaurant->delete();

        return redirect()->route('backend.index');
    }
}

application/resources/views/frontend/index.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Finder')

@section('content')
    <div class="col-xs-1 text-center mt-3">
        <h3>
            Restaurant Search
        </h3>
        <button onclick="getClientsLocation()">Get Current Location</button>
        <input id="location" type="text" />
        <button type="submit" onclick="renderDirections(restaurants_locations)">Go</button>
    </div>
    <!--The div element for the map -->
    <div id="map"></div>
    <script>
        var restaurants_locations = {!! json_encode($restaurants->pluck('location')) !!};
    </script>
    <script src="/js/mapping.js"></script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{ config('app.google_map_api_key') }}&callback=initMap">
    </script>

@endsection

application/resources/views/layouts/app.blade.php
<html>
    <head>
        <title>Crowd Property - @yield('title')</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/style.css">
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

application/resources/views/restaurantadmin/create.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Admin - Create')

@section('content')
    <h4>Restaurant Admin - Create</h4>
    <form action="{{ route('backend.store') }}" method="POST">
        @csrf

        <label for="name">Name: </label>
        <input id="name" type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Restaurant name" required />
        @if ($errors->has('name'))
            <div class="text-danger">{{ $errors->first('name') }}</div>
        @endif
        <br />
        <label for="location">Location: </label>
        <input type="text" id="location" name="location" value="{{ old('location') }}" class="form-control" placeholder="Restaurant location" required />
        @if ($errors->has('location'))
            <div class="text-danger">{{ $errors->first('location') }}</div>
        @endif
        <br />
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
@endsection

application/resources/views/restaurantadmin/edit.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Admin - Edit')

@section('content')
    <h4>Restaurant Admin - Edit</h4>
    <form action="{{ route('backend.update', $restaurant->id) }}" method="POST">
        @method('PUT')
        @csrf

        <label for="name">Name: </label>
        <input id="name" type="text" name="name" value="{{ old('name', $restaurant->name) }}" class="form-control" placeholder="Restaurant name" />
        @if ($errors->has('name'))
            <div class="text-danger">{{ $errors->first('name') }}</div>
        @endif
        <br />
        <label for="location">Location: </label>
        <input type="text" id="location" name="location" value="{{ old('restaurant', $restaurant->location) }}" class="form-control" placeholder="Restaurant location" />
        @if ($errors->has('location'))
            <div class="text-danger">{{ $errors->first('location') }}</div>
        @endif
        <br />
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
@endsection

application/resources/views/restaurantadmin/index.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Admin - Index')

@section('content')
    <h4>Restaurant Admin - Index</h4>
    <div class="pb-3">
        <a class="btn btn-primary" href="{{ route('backend.create') }}">Add Restaurant</a>
    </div>

    @forelse ($restaurants as $restaurant)
        @if ($loop->first)
            <table class="table table-striped">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th colspan="3" style="width: 10%">Actions</th>
            </tr>
        @endif
        <tr>
            <td>{{ $restaurant->name }}</td>
            <td>{{ $restaurant->location }}</td>
            <td><a class="btn btn-primary" href="{{ route('backend.show', $restaurant->id) }}">View</a></td>
            <td><a class="btn btn-primary" href="{{ route('backend.edit', $restaurant->id) }}">Edit</a></td>
            <td>
                <form method="post" action="{{ route('backend.destroy', $restaurant->id) }}">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-primary">Delete</button>
                </form>
            </td>

        </tr>
        @if ($loop->last)
            </table>
        @endif
    @empty
        No Restaurants
    @endforelse
@endsection

application/resources/views/restaurantadmin/show.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Admin - Index')

@section('content')
    <h4>Restaurant Admin - View</h4>
    <b>Name:</b> {{ $restaurant->name }}
    <br />
    <b>Location:</b> {{ $restaurant->location }}
    <br />
    <a class="btn btn-primary mb-3" href="{{ route('backend.edit', $restaurant->id) }}">Edit</a>
    <br />
    <form method="post" action="{{ route('backend.destroy', $restaurant->id) }}">
        @csrf
        @method('DELETE')
        <button class="btn btn-primary" type="submit">Delete</button>
    </form>
@endsection